Route List
+---------------------------------------------------------+----------------------------------------+--------+----------------------------------------+
| Rule                                                    | Route                                  | Method | Name                                   |
+---------------------------------------------------------+----------------------------------------+--------+----------------------------------------+
| api/admin/login                                         | Login/login                            | post   | AdminLogin                             |
| api/admin/login/info                                    | Login/info                             | get    | Login/info                             |
| api/admin/download                                      | PublicController/download              | get    | PublicController/download              |
| api/admin/captcha_pro                                   | Login/captcha                          | get    |                                        |
| api/admin/ajcaptcha                                     | Login/ajcaptcha                        | get    | ajcaptcha                              |
| api/admin/ajcheck                                       | Login/ajcheck                          | post   | ajcheck                                |
| api/admin/logo                                          | Index/logo                             | get    | Index/logo                             |
| api/admin/jnotice                                       | Index/jnotice                          | get    | Index/jnotice                          |
| api/admin/menusList                                     | Index/getMenusList                     | get    | Index/getMenusList                     |
| api/admin/app/reset/<id>                                | Application/reset                      | put    | Application/reset                      |
| api/admin/app                                           | Application/index                      | get    | Application/index                      |
| api/admin/app                                           | Application/save                       | post   | Application/save                       |
| api/admin/app/create                                    | Application/create                     | get    | Application/create                     |
| api/admin/app/<id>/edit                                 | Application/edit                       | get    | Application/edit                       |
| api/admin/app/<id>                                      | Application/read                       | get    | Application/read                       |
| api/admin/app/<id>                                      | Application/update                     | put    | Application/update                     |
| api/admin/app/<id>                                      | Application/delete                     | delete | Application/delete                     |
| api/admin/chart/sum                                     | Index/sum                              | get    | Index/sum                              |
| api/admin/chart                                         | Index/index                            | get    | Index/index                            |
| api/admin/chat/statistics                               | SiteStatistics/index                   | get    | SiteStatistics/index                   |
| api/admin/chat/qrcode                                   | Qrcode/index                           | get    | Qrcode/index                           |
| api/admin/chat/qrcode/<id>                              | Qrcode/create                          | get    | Qrcode/create                          |
| api/admin/chat/qrcode/<id>                              | Qrcode/save                            | post   | Qrcode/save                            |
| api/admin/chat/qrcode/<id>                              | Qrcode/delete                          | delete | Qrcode/delete                          |
| api/admin/chat/kefu                                     | Service/index                          | get    | Service/index                          |
| api/admin/chat/kefu                                     | Service/save                           | post   | Service/save                           |
| api/admin/chat/group                                    | ServiceGroup/index                     | get    | ServiceGroup/index                     |
| api/admin/chat/group/create/<id>                        | ServiceGroup/create                    | get    | ServiceGroup/create                    |
| api/admin/chat/group/<id>                               | ServiceGroup/save                      | post   | ServiceGroup/save                      |
| api/admin/chat/group/<id>                               | ServiceGroup/delete                    | delete | ServiceGroup/delete                    |
| api/admin/chat/reply                                    | AutoReply/index                        | get    | AutoReply/index                        |
| api/admin/chat/reply/<id>                               | AutoReply/create                       | get    | AutoReply/create                       |
| api/admin/chat/reply/<id>                               | AutoReply/save                         | post   | AutoReply/save                         |
| api/admin/chat/reply/<id>                               | AutoReply/delete                       | delete | AutoReply/delete                       |
| api/admin/chat/kefu/login/<id>                          | Service/keufLogin                      | get    | Service/keufLogin                      |
| api/admin/chat/kefu/add                                 | Service/add                            | get    | Service/add                            |
| api/admin/chat/kefu/<id>/edit                           | Service/edit                           | get    | Service/edit                           |
| api/admin/chat/kefu/<id>                                | Service/update                         | put    | Service/update                         |
| api/admin/chat/kefu/<id>                                | Service/delete                         | delete | Service/delete                         |
| api/admin/chat/kefu/set_status/<id>/<status>            | Service/set_status                     | put    | Service/set_status                     |
| api/admin/chat/kefu/record/<id>                         | Service/chat_user                      | get    | Service/chat_user                      |
| api/admin/chat/kefu/chat_list                           | Service/chat_list                      | get    | Service/chat_list                      |
| api/admin/chat/record                                   | ServiceDialogueRecord/index            | get    | ServiceDialogueRecord/index            |
| api/admin/chat/record/list                              | ServiceDialogueRecord/record           | get    | ServiceDialogueRecord/record           |
| api/admin/chat/record_kefu                              | ServiceDialogueRecord/kefu             | get    | ServiceDialogueRecord/kefu             |
| api/admin/chat/speechcraft                              | ServiceSpeechcraft/index               | get    | ServiceSpeechcraft/index               |
| api/admin/chat/speechcraft                              | ServiceSpeechcraft/save                | post   | ServiceSpeechcraft/save                |
| api/admin/chat/speechcraft/create                       | ServiceSpeechcraft/create              | get    | ServiceSpeechcraft/create              |
| api/admin/chat/speechcraft/<id>/edit                    | ServiceSpeechcraft/edit                | get    | ServiceSpeechcraft/edit                |
| api/admin/chat/speechcraft/<id>                         | ServiceSpeechcraft/read                | get    | ServiceSpeechcraft/read                |
| api/admin/chat/speechcraft/<id>                         | ServiceSpeechcraft/update              | put    | ServiceSpeechcraft/update              |
| api/admin/chat/speechcraft/<id>                         | ServiceSpeechcraft/delete              | delete | ServiceSpeechcraft/delete              |
| api/admin/chat/speechcraftcate                          | ServiceSpeechcraftCate/index           | get    | ServiceSpeechcraftCate/index           |
| api/admin/chat/speechcraftcate                          | ServiceSpeechcraftCate/save            | post   | ServiceSpeechcraftCate/save            |
| api/admin/chat/speechcraftcate/create                   | ServiceSpeechcraftCate/create          | get    | ServiceSpeechcraftCate/create          |
| api/admin/chat/speechcraftcate/<id>/edit                | ServiceSpeechcraftCate/edit            | get    | ServiceSpeechcraftCate/edit            |
| api/admin/chat/speechcraftcate/<id>                     | ServiceSpeechcraftCate/read            | get    | ServiceSpeechcraftCate/read            |
| api/admin/chat/speechcraftcate/<id>                     | ServiceSpeechcraftCate/update          | put    | ServiceSpeechcraftCate/update          |
| api/admin/chat/speechcraftcate/<id>                     | ServiceSpeechcraftCate/delete          | delete | ServiceSpeechcraftCate/delete          |
| api/admin/chat/feedback                                 | ServiceFeedback/index                  | get    | ServiceFeedback/index                  |
| api/admin/chat/feedback                                 | ServiceFeedback/save                   | post   | ServiceFeedback/save                   |
| api/admin/chat/feedback/create                          | ServiceFeedback/create                 | get    | ServiceFeedback/create                 |
| api/admin/chat/feedback/<id>/edit                       | ServiceFeedback/edit                   | get    | ServiceFeedback/edit                   |
| api/admin/chat/feedback/<id>                            | ServiceFeedback/read                   | get    | ServiceFeedback/read                   |
| api/admin/chat/feedback/<id>                            | ServiceFeedback/update                 | put    | ServiceFeedback/update                 |
| api/admin/chat/feedback/<id>                            | ServiceFeedback/delete                 | delete | ServiceFeedback/delete                 |
| api/admin/user/index                                    | User/index                             | get    | User/index                             |
| api/admin/user/user_label                               | User/getLavelAll                       | get    | User/getLavelAll                       |
| api/admin/user/edit/<id>                                | User/edit                              | get    | User/edit                              |
| api/admin/user/update/<id>                              | User/update                            | put    | User/update                            |
| api/admin/user/batch/label                              | User/batchLabel                        | put    | User/batchLabel                        |
| api/admin/user/batch/group                              | User/batchGroup                        | put    | User/batchGroup                        |
| api/admin/user/label/all                                | User/getLabelAll                       | get    | User/getLabelAll                       |
| api/admin/user/group/all                                | User/getGroupAll                       | get    | User/getGroupAll                       |
| api/admin/user/label/move                               | Label/move                             | post   | Label/move                             |
| api/admin/user/label/move_cate                          | LabelCate/move                         | post   | LabelCate/move                         |
| api/admin/user/label/cate                               | LabelCate/index                        | get    | LabelCate/index                        |
| api/admin/user/label/cate                               | LabelCate/save                         | post   | LabelCate/save                         |
| api/admin/user/label/cate/create                        | LabelCate/create                       | get    | LabelCate/create                       |
| api/admin/user/label/cate/<id>/edit                     | LabelCate/edit                         | get    | LabelCate/edit                         |
| api/admin/user/label/cate/<id>                          | LabelCate/read                         | get    | LabelCate/read                         |
| api/admin/user/label/cate/<id>                          | LabelCate/update                       | put    | LabelCate/update                       |
| api/admin/user/label/cate/<id>                          | LabelCate/delete                       | delete | LabelCate/delete                       |
| api/admin/user/label                                    | Label/index                            | get    | Label/index                            |
| api/admin/user/label                                    | Label/save                             | post   | Label/save                             |
| api/admin/user/label/create                             | Label/create                           | get    | Label/create                           |
| api/admin/user/label/<id>/edit                          | Label/edit                             | get    | Label/edit                             |
| api/admin/user/label/<id>                               | Label/read                             | get    | Label/read                             |
| api/admin/user/label/<id>                               | Label/update                           | put    | Label/update                           |
| api/admin/user/label/<id>                               | Label/delete                           | delete | Label/delete                           |
| api/admin/user/group                                    | Group/index                            | get    | Group/index                            |
| api/admin/user/group                                    | Group/save                             | post   | Group/save                             |
| api/admin/user/group/create                             | Group/create                           | get    | Group/create                           |
| api/admin/user/group/<id>/edit                          | Group/edit                             | get    | Group/edit                             |
| api/admin/user/group/<id>                               | Group/read                             | get    | Group/read                             |
| api/admin/user/group/<id>                               | Group/update                           | put    | Group/update                           |
| api/admin/user/group/<id>                               | Group/delete                           | delete | Group/delete                           |
| api/admin/file/file                                     | Attachment/index                       | get    | Attachment/index                       |
| api/admin/file/file/delete                              | Attachment/delete                      | post   | Attachment/delete                      |
| api/admin/file/file/move                                | Attachment/move                        | get    | Attachment/move                        |
| api/admin/file/file/do_move                             | Attachment/moveImageCate               | put    | Attachment/moveImageCate               |
| api/admin/file/file/update/<id>                         | Attachment/update                      | put    | Attachment/update                      |
| api/admin/file/upload/<upload_type?>                    | Attachment/upload                      | post   | Attachment/upload                      |
| api/admin/file/category                                 | AttachmentCategory/index               | get    | AttachmentCategory/index               |
| api/admin/file/category                                 | AttachmentCategory/save                | post   | AttachmentCategory/save                |
| api/admin/file/category/create                          | AttachmentCategory/create              | get    | AttachmentCategory/create              |
| api/admin/file/category/<id>/edit                       | AttachmentCategory/edit                | get    | AttachmentCategory/edit                |
| api/admin/file/category/<id>                            | AttachmentCategory/read                | get    | AttachmentCategory/read                |
| api/admin/file/category/<id>                            | AttachmentCategory/update              | put    | AttachmentCategory/update              |
| api/admin/file/category/<id>                            | AttachmentCategory/delete              | delete | AttachmentCategory/delete              |
| api/admin/system/log                                    | system.Log/index                       | get    | SystemLog                              |
| api/admin/system/log/search_admin                       | system.Log/search_admin                | get    | system.Log/search_admin                |
| api/admin/tenant/list                                   | tenant.Tenant/index                    | get    | TenantList                             |
| api/admin/tenant/info/<id>                              | tenant.Tenant/read                     | get    | TenantInfo                             |
| api/admin/tenant/save                                   | tenant.Tenant/save                     | post   | TenantSave                             |
| api/admin/tenant/update/<id>                            | tenant.Tenant/update                   | put    | TenantUpdate                           |
| api/admin/tenant/delete/<id>                            | tenant.Tenant/delete                   | delete | TenantDelete                           |
| api/admin/tenant/status/<id>                            | tenant.Tenant/updateStatus             | put    | TenantUpdateStatus                     |
| api/admin/tenant/batch_status                           | tenant.Tenant/batchUpdateStatus        | put    | TenantBatchUpdateStatus                |
| api/admin/tenant/statistics                             | tenant.Tenant/statistics               | get    | TenantStatistics                       |
| api/admin/tenant/expiring                               | tenant.Tenant/expiring                 | get    | TenantExpiring                         |
| api/admin/tenant/status_options                         | tenant.Tenant/statusOptions            | get    | TenantStatusOptions                    |
| api/admin/tenant/check_unique                           | tenant.Tenant/checkUnique              | get    | TenantCheckUnique                      |
| api/admin/setting/verison                               | system.AppVersion/index                | get    | AppVerisonIndex                        |
| api/admin/setting/verison/<id>                          | system.AppVersion/delete               | delete | AppVerisonDelete                       |
| api/admin/setting/verison/<id>                          | system.AppVersion/create               | get    | AppVerisonCreate                       |
| api/admin/setting/verison/save/<id>                     | system.AppVersion/save                 | post   | AppVerisonSave                         |
| api/admin/setting/admin/logout                          | system.Admin/logout                    | get    | SystemAdminLogout                      |
| api/admin/setting/set_status/<id>/<status>              | system.Admin/set_status                | put    | SystemAdminSetStatus                   |
| api/admin/setting/info                                  | system.Admin/info                      | get    | SystemAdminInfo                        |
| api/admin/setting/update_admin                          | system.Admin/update_admin              | put    | SystemAdminUpdateAdmin                 |
| api/admin/setting/menus/show/<id>                       | system.Menus/show                      | put    | SystemMenusShow                        |
| api/admin/setting/role                                  | system.Role/index                      | get    | system.Role/index                      |
| api/admin/setting/role/create                           | system.Role/create                     | get    | system.Role/create                     |
| api/admin/setting/role/<id>/edit                        | system.Role/edit                       | get    | system.Role/edit                       |
| api/admin/setting/role/<id>                             | system.Role/save                       | post   | system.Role/save                       |
| api/admin/setting/role/<id>                             | system.Role/delete                     | delete | system.Role/delete                     |
| api/admin/setting/role/set_status/<id>/<status>         | system.Role/set_status                 | put    | system.Role/set_status                 |
| api/admin/setting/config_class/set_status/<id>/<status> | system.ConfigTab/set_status            | put    | system.ConfigTab/set_status            |
| api/admin/setting/config/set_status/<id>/<status>       | system.Config/set_status               | put    | system.Config/set_status               |
| api/admin/setting/config/header_basics                  | system.Config/header_basics            | get    | system.Config/header_basics            |
| api/admin/setting/config/edit_basics                    | system.Config/edit_basics              | get    | system.Config/edit_basics              |
| api/admin/setting/config/save_basics                    | system.Config/save_basics              | post   | system.Config/save_basics              |
| api/admin/setting/config/upload                         | system.Config/file_upload              | post   | system.Config/file_upload              |
| api/admin/setting/config/kefu                           | system.Config/getKefuIcon              | get    | system.Config/getKefuIcon              |
| api/admin/setting/config/kefu                           | system.Config/setKefuIcon              | post   | system.Config/setKefuIcon              |
| api/admin/setting/group_all                             | system.Group/getGroup                  | get    | system.Group/getGroup                  |
| api/admin/setting/group_data/header                     | system.GroupData/header                | get    | system.GroupData/header                |
| api/admin/setting/group_data/set_status/<id>/<status>   | system.GroupData/set_status            | put    | system.GroupData/set_status            |
| api/admin/setting/get_kf_adv                            | system.GroupData/getKfAdv              | get    | system.GroupData/getKfAdv              |
| api/admin/setting/set_kf_adv                            | system.GroupData/setKfAdv              | post   | system.GroupData/setKfAdv              |
| api/admin/setting/get_user_agreement                    | system.GroupData/getUserAgreement      | get    | system.GroupData/getUserAgreement      |
| api/admin/setting/set_user_agreement                    | system.GroupData/setUserAgreement      | post   | system.GroupData/setUserAgreement      |
| api/admin/setting/ruleList                              | system.Menus/ruleList                  | get    | system.Menus/ruleList                  |
| api/admin/setting/group                                 | system.Group/index                     | get    | system.Group/index                     |
| api/admin/setting/group                                 | system.Group/save                      | post   | system.Group/save                      |
| api/admin/setting/group/create                          | system.Group/create                    | get    | system.Group/create                    |
| api/admin/setting/group/<id>/edit                       | system.Group/edit                      | get    | system.Group/edit                      |
| api/admin/setting/group/<id>                            | system.Group/read                      | get    | system.Group/read                      |
| api/admin/setting/group/<id>                            | system.Group/update                    | put    | system.Group/update                    |
| api/admin/setting/group/<id>                            | system.Group/delete                    | delete | system.Group/delete                    |
| api/admin/setting/group_data                            | system.GroupData/index                 | get    | system.GroupData/index                 |
| api/admin/setting/group_data                            | system.GroupData/save                  | post   | system.GroupData/save                  |
| api/admin/setting/group_data/create                     | system.GroupData/create                | get    | system.GroupData/create                |
| api/admin/setting/group_data/<id>/edit                  | system.GroupData/edit                  | get    | system.GroupData/edit                  |
| api/admin/setting/group_data/<id>                       | system.GroupData/read                  | get    | system.GroupData/read                  |
| api/admin/setting/group_data/<id>                       | system.GroupData/update                | put    | system.GroupData/update                |
| api/admin/setting/group_data/<id>                       | system.GroupData/delete                | delete | system.GroupData/delete                |
| api/admin/setting/config_class                          | system.ConfigTab/index                 | get    | system.ConfigTab/index                 |
| api/admin/setting/config_class                          | system.ConfigTab/save                  | post   | system.ConfigTab/save                  |
| api/admin/setting/config_class/create                   | system.ConfigTab/create                | get    | system.ConfigTab/create                |
| api/admin/setting/config_class/<id>/edit                | system.ConfigTab/edit                  | get    | system.ConfigTab/edit                  |
| api/admin/setting/config_class/<id>                     | system.ConfigTab/read                  | get    | system.ConfigTab/read                  |
| api/admin/setting/config_class/<id>                     | system.ConfigTab/update                | put    | system.ConfigTab/update                |
| api/admin/setting/config_class/<id>                     | system.ConfigTab/delete                | delete | system.ConfigTab/delete                |
| api/admin/setting/config                                | system.Config/index                    | get    | system.Config/index                    |
| api/admin/setting/config                                | system.Config/save                     | post   | system.Config/save                     |
| api/admin/setting/config/create                         | system.Config/create                   | get    | system.Config/create                   |
| api/admin/setting/config/<id>/edit                      | system.Config/edit                     | get    | system.Config/edit                     |
| api/admin/setting/config/<id>                           | system.Config/read                     | get    | system.Config/read                     |
| api/admin/setting/config/<id>                           | system.Config/update                   | put    | system.Config/update                   |
| api/admin/setting/config/<id>                           | system.Config/delete                   | delete | system.Config/delete                   |
| api/admin/setting/menus                                 | system.Menus/index                     | get    | system.Menus/index                     |
| api/admin/setting/menus                                 | system.Menus/save                      | post   | system.Menus/save                      |
| api/admin/setting/menus/create                          | system.Menus/create                    | get    | system.Menus/create                    |
| api/admin/setting/menus/<id>/edit                       | system.Menus/edit                      | get    | system.Menus/edit                      |
| api/admin/setting/menus/<id>                            | system.Menus/read                      | get    | system.Menus/read                      |
| api/admin/setting/menus/<id>                            | system.Menus/update                    | put    | system.Menus/update                    |
| api/admin/setting/menus/<id>                            | system.Menus/delete                    | delete | system.Menus/delete                    |
| api/admin/setting/admin                                 | system.Admin/index                     | get    | system.Admin/index                     |
| api/admin/setting/admin                                 | system.Admin/save                      | post   | system.Admin/save                      |
| api/admin/setting/admin/create                          | system.Admin/create                    | get    | system.Admin/create                    |
| api/admin/setting/admin/<id>/edit                       | system.Admin/edit                      | get    | system.Admin/edit                      |
| api/admin/setting/admin/<id>                            | system.Admin/read                      | get    | system.Admin/read                      |
| api/admin/setting/admin/<id>                            | system.Admin/update                    | put    | system.Admin/update                    |
| api/admin/setting/admin/<id>                            | system.Admin/delete                    | delete | system.Admin/delete                    |
| api/admin<MISS>                                         | <Closure>                              | *      |                                        |
| api/kefu/service/ping                                   | Service/ping                           | get    | ping                                   |
| api/kefu/ticket/<appid?>                                | Login/ticket                           | *      | Login/ticket                           |
| api/kefu/login                                          | Login/login                            | post   | kefuLogin                              |
| api/kefu/key                                            | Login/getLoginKey                      | get    | getLoginKey                            |
| api/kefu/scan/<key>                                     | Login/scanLogin                        | get    | scanLogin                              |
| api/kefu/config                                         | Login/getAppid                         | get    | getAppid                               |
| api/kefu/agreement                                      | User/getUserAgreement                  | get    | getUserAgreement                       |
| api/kefu/upload                                         | User/upload                            | post   | upload                                 |
| api/kefu/version                                        | Service/version                        | post   | version                                |
| api/kefu/user/list                                      | User/getUserList                       | get    | getUserList                            |
| api/kefu/user/record                                    | User/recordList                        | get    | recordList                             |
| api/kefu/user/recordAll                                 | User/recordAllList                     | get    | recordAllList                          |
| api/kefu/user/record/<id>                               | User/deleteRecordUser                  | delete | deleteRecordUser                       |
| api/kefu/user/count                                     | User/getMessageCount                   | get    | getMessageCount                        |
| api/kefu/user/info/<userId>                             | User/userInfo                          | get    | getUserInfo                            |
| api/kefu/user/label                                     | User/getUserLabel                      | get    | getUserLabel                           |
| api/kefu/user/label/all                                 | User/getLabelAll                       | get    | getLabelAll                            |
| api/kefu/user/label/<userId>                            | User/setUserLabel                      | put    | setUserLabel                           |
| api/kefu/user/label/<userId>/<labelId>                  | User/delUserLabel                      | delete | delUserLabel                           |
| api/kefu/user/group                                     | User/getUserGroup                      | get    | getUserGroup                           |
| api/kefu/user/group/<userId>/<id>                       | User/setUserGroup                      | put    | setUserGroup                           |
| api/kefu/user/logout                                    | User/logout                            | post   | logout                                 |
| api/kefu/user/userInfo                                  | User/getKefuInfo                       | get    | getKefuInfo                            |
| api/kefu/user/userInfo                                  | User/updateKefu                        | put    | updateKefu                             |
| api/kefu/user/updateUser/<userId>                       | User/updateUser                        | put    | updateUser                             |
| api/kefu/user/client                                    | User/updateService                     | put    | updateService                          |
| api/kefu/user/feedback                                  | User/saveFeedback                      | post   | saveFeedback                           |
| api/kefu/user/complain                                  | User/getComplainList                   | get    | getComplainList                        |
| api/kefu/user/complain                                  | User/complain                          | post   | complain                               |
| api/kefu/user/status/<userId>                           | User/status                            | put    | status                                 |
| api/kefu/user/savelog                                   | User/savelog                           | post   | savelog                                |
| api/kefu/statistics/all                                 | Statistics/sum                         | get    | kefuStatisticsSum                      |
| api/kefu/statistics/index                               | Statistics/index                       | get    | kefuStatisticsIndex                    |
| api/kefu/service/code                                   | Service/setLoginCode                   | post   | setLoginCode                           |
| api/kefu/service/list                                   | Service/getChatList                    | get    | getChatList                            |
| api/kefu/service/info                                   | Service/getServiceInfo                 | get    | getServiceInfo                         |
| api/kefu/service/speechcraft                            | Service/getSpeechcraftList             | get    | getSpeechcraftList                     |
| api/kefu/service/speechcraft                            | Service/saveSpeechcraft                | post   | saveSpeechcraft                        |
| api/kefu/service/transfer                               | Service/transfer                       | post   | transfer                               |
| api/kefu/service/transfer_list                          | Service/getServiceList                 | get    | getServiceList                         |
| api/kefu/service/cate                                   | Service/getCateList                    | get    | getCateList                            |
| api/kefu/service/cate                                   | Service/saveCate                       | post   | saveCate                               |
| api/kefu/service/cate/<id>                              | Service/editCate                       | put    | editCate                               |
| api/kefu/service/cate/<id>                              | Service/deleteCate                     | delete | deleteCate                             |
| api/kefu/service/speechcraft/<id>                       | Service/editSpeechcraft                | put    | editSpeechcraft                        |
| api/kefu/service/speechcraft/<id>                       | Service/deleteSpeechcraft              | delete | deleteSpeechcraft                      |
| api/kefu/service/auth_reply                             | Service/getAuthReply                   | get    | getAuthReply                           |
| api/kefu/service/auth_reply/<id>                        | Service/saveAuthReply                  | post   | saveAuthReply                          |
| api/kefu/service/auth_reply/<id>                        | Service/deleteAuthReply                | delete | deleteAuthReply                        |
| api/kefu/service/auth_reply/<value>                     | Service/setAutoReply                   | put    | setAutoReply                           |
| api/kefu/service/backstage/<backstage>                  | Service/backstage                      | put    | backstage                              |
| api/kefu/service/get_send_id                            | Service/getSendId                      | get    | getSendId                              |
| api/kefu/service/send_message                           | Service/sendMessage                    | post   | sendMessage                            |
| api/kefu<MISS>                                          | <Closure>                              | *      |                                        |
| api/mobile/service/ping                                 | Comment/ping                           | get    | ping                                   |
| api/mobile/user/record                                  | Service/getRecordList                  | get    | Service/getRecordList                  |
| api/mobile/user/statistics                              | Statistics/save                        | post   | Statistics/save                        |
| api/mobile/service/icon                                 | Service/getKefuConfig                  | get    | getKefuConfig                          |
| api/mobile/service/adv                                  | Service/getKfAdv                       | get    | getKfAdv                               |
| api/mobile/service/feedback                             | Feedback/saveFeedback                  | post   | saveFeedback                           |
| api/mobile/service/feedback                             | Feedback/getFeedbackInfo               | get    | getFeedbackInfo                        |
| api/mobile/service/upload                               | Service/upload                         | post   | upload                                 |
| api/mobile/service/cache/<key>                          | Service/getCache                       | get    | getCache                               |
| api/mobile/service/cache                                | Service/setCache                       | post   | setCache                               |
| api/mobile/service/get_send_id                          | Service/getSendId                      | get    | getSendId                              |
| api/mobile/service/send_message                         | Service/sendMessage                    | post   | sendMessage                            |
| api/mobile<MISS>                                        | <Closure>                              | *      |                                        |
| install/index                                           | InstallController/index                | post   | InstallController/index                |
| upgrade/index                                           | UpgradeController/index                | get    | UpgradeController/index                |
| upgrade/upgrade                                         | UpgradeController/upgrade              | get    | UpgradeController/upgrade              |
| <MISS>                                                  | <Closure>                              | *      |                                        |
| api/tenant/login                                        | Login/login                            | post   | TenantLogin                            |
| api/tenant/info                                         | Login/info                             | get    | Login/info                             |
| api/tenant/logout                                       | Login/logout                           | post   | Login/logout                           |
| api/tenant/change_password                              | Login/changePassword                   | post   | Login/changePassword                   |
| api/tenant/user/list                                    | User/index                             | get    | User/index                             |
| api/tenant/user/info/<id>                               | User/read                              | get    | User/read                              |
| api/tenant/user/save                                    | User/save                              | post   | User/save                              |
| api/tenant/user/update/<id>                             | User/update                            | put    | User/update                            |
| api/tenant/user/delete/<id>                             | User/delete                            | delete | User/delete                            |
| api/tenant/user/status/<id>                             | User/updateStatus                      | put    | User/updateStatus                      |
| api/tenant/service/list                                 | Service/index                          | get    | Service/index                          |
| api/tenant/service/info/<id>                            | Service/read                           | get    | Service/read                           |
| api/tenant/service/save                                 | Service/save                           | post   | Service/save                           |
| api/tenant/service/update/<id>                          | Service/update                         | put    | Service/update                         |
| api/tenant/service/delete/<id>                          | Service/delete                         | delete | Service/delete                         |
| api/tenant/service/status/<id>                          | Service/updateStatus                   | put    | Service/updateStatus                   |
| api/tenant/statistics/overview                          | Statistics/overview                    | get    | Statistics/overview                    |
| api/tenant/statistics/users                             | Statistics/users                       | get    | Statistics/users                       |
| api/tenant/statistics/services                          | Statistics/services                    | get    | Statistics/services                    |
| captcha/<config?>                                       | \think\captcha\CaptchaController@index | get    | \think\captcha\CaptchaController@index |
+---------------------------------------------------------+----------------------------------------+--------+----------------------------------------+
