package io.renren.modules.kefu.controller.admin;

import io.renren.modules.kefu.dto.admin.AdminLoginDTO;
import io.renren.modules.kefu.dto.admin.AjCheckDTO;
import io.renren.modules.kefu.service.AdminCaptchaService;
import io.renren.modules.kefu.vo.ApiResponse;
import io.renren.modules.kefu.vo.admin.AdminLoginVO;
import io.renren.modules.kefu.vo.admin.LoginInfoVO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletResponse;
import lombok.AllArgsConstructor;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.util.Map;
import java.util.UUID;

/**
 * Admin API - 认证相关
 *
 * @author AutoGenerated
 * @date 2025-01-01
 */
@RestController
@RequestMapping("/api/admin")
@AllArgsConstructor
@Tag(name = "Admin - 认证管理")
public class AdminAuthController {

    private final AdminCaptchaService adminCaptchaService;

    /**
     * 1.1 管理员登录
     * POST /api/admin/login
     */
    @PostMapping("/login")
    @Operation(summary = "管理员登录")
    public ApiResponse<AdminLoginVO> login(@RequestBody AdminLoginDTO dto) {
        // TODO: 实现登录逻辑
        throw new UnsupportedOperationException("Not implemented yet");
    }

    /**
     * 1.2 获取登录信息
     * GET /api/admin/login/info
     */
    @GetMapping("/login/info")
    @Operation(summary = "获取登录页信息")
    public ApiResponse<LoginInfoVO> getLoginInfo() {
        LoginInfoVO loginInfo = new LoginInfoVO();
        loginInfo.setSystemName("CRM Chat Admin");
        loginInfo.setLogoUrl("/img/logo.png");
        loginInfo.setCaptchaEnabled(true);
        loginInfo.setCaptchaType("ajcaptcha");
        loginInfo.setTenantEnabled(true);
        loginInfo.setBackgroundUrl("/img/bg.jpg");

        return ApiResponse.success(loginInfo);
    }

    /**
     * 1.3 获取验证码
     * GET /api/admin/captcha_pro
     */
    @GetMapping("/captcha_pro")
    @Operation(summary = "获取图片验证码")
    public void getCaptcha(@Parameter(description = "验证码UUID") @RequestParam(required = false) String uuid,
                           HttpServletResponse response) throws IOException {
        if (uuid == null || uuid.isEmpty()) {
            uuid = UUID.randomUUID().toString();
        }
        adminCaptchaService.createCaptcha(response, uuid);
    }

    /**
     * 1.4 获取AJ验证码
     * GET /api/admin/ajcaptcha
     */
    @GetMapping("/ajcaptcha")
    @Operation(summary = "获取滑块验证码")
    public ApiResponse<Map<String, Object>> getAjCaptcha(
            @Parameter(description = "验证码类型") @RequestParam(defaultValue = "blockPuzzle") String captchaType) {
        Map<String, Object> result = adminCaptchaService.createAjCaptcha(captchaType);
        return ApiResponse.success(result);
    }

    /**
     * 1.5 验证码验证
     * POST /api/admin/ajcheck
     */
    @PostMapping("/ajcheck")
    @Operation(summary = "验证滑块验证码")
    public ApiResponse<Map<String, Object>> ajCheck(@RequestBody AjCheckDTO dto) {
        Map<String, Object> result = adminCaptchaService.checkAjCaptcha(dto);
        return ApiResponse.success(result);
    }
}
